snuhcs-course/swpp-2023-project-team-18

- backend/moment/moment/settings.py
> chore: Add newline just to test deploy

- .gitignore
- backend/.vscode/settings.json
* gitignore에 이미 vscode 관련 파일들이 들어 있어서, 중복된 entry를 제거
* 이에 따라 `.vscode/settings.json`이 remote에서 관리됨
None
> chore: Update gitignore

- backend/Dockerfile
- backend/config/requirements.txt
- backend/docker-compose.yml
- backend/moment/moment/settings.py
- backend/moment/writing/cron.py
- backend/moment/writing/tests.py
하루 자동 마무리 로직 구현했습니다. cron.py에 있는 auto_completion_job이 새벽 3시마다 실행됩니다. 로그는 cron.log에 기록되게 해두었어요.
dockerfile 과 compose 파일이 cron job 실행을 위해 바뀌었습니다.
> implement auto completion

- backend/moment/writing/serializers.py
- backend/moment/writing/tests.py
story view에서 해시태그를 함께 주도록 바꾸었습니다.
None
> get story view fix

- backend/moment/writing/cron.py
- backend/moment/writing/tests.py
자동 생성시 created_at을 시간대 고려해서 수정했습니다.
None
>  Fix auto completion created at considering timezone

- backend/moment/writing/serializers.py
- backend/moment/writing/tests.py
- backend/moment/writing/views.py
프론트엔드 testing을 수월하게 하기 위해 story delete api를 만들었습니다.
testing할때만 사용하고, 실제 앱에서는 절대 사용되면 안되는 api이니 유의해 주세요.
api document도 업데이트했습니다. 확인하시고 그거 기반으로 pr 리뷰해주세요
> feat: Add story delete api

- backend/moment/writing/utils/log.py
- backend/moment/writing/views.py
디버깅을 쉽게 하기 위해 api log들을 추가했습니다.
None
> feat: Add logs in views

- backend/moment/user/tests.py
- backend/moment/writing/tests.py
모먼트 및 User view 테스트 코드 작성했습니다.
None
> Backend/testing: Write tests for Views Written in Iteration 2

- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/DailyViewModelTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/GetStoryUseCaseTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/SaveScoreUseCaseTest.java
import가 빠져서 test가 안 돌아가는 문제가 있어 해결했습니다.
> fix: Fix import statements in test code after merge in p21

- backend/moment/scripts/run_gpt.py
- backend/moment/writing/cron.py
- backend/moment/writing/utils/prompt.py
- backend/moment/writing/views.py
- 제목 자수 제한을 추가한 prompt 올려드립니다.
- run_gpt.py로 직접 prompt 돌려보실 수 있도록 코드 짜두었습니다.
None
> Backend/p13_prompt Prompt engineering for ai story generation

- backend/moment/writing/cron.py
- backend/moment/writing/serializers.py
- backend/moment/writing/tests.py
- backend/moment/writing/views.py
중복된 Hashtag Model 객체를 만들지 않도록 수정했습니다.
hashtag view GET 시 story id 대신 start, end timestamp를 받도록 수정했습니다.
None
> backend/hashtag fix: Fix Hashtag View

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/TodayViewFragment.java
밤 12시가 지났을 때 오늘 탭의 날짜가 잘못 표시되는 문제를 수정했습니다.
None
> 오늘 탭 날짜 표시 수정

- backend/moment/writing/constants.py
- backend/moment/writing/search_serializers.py
- backend/moment/writing/search_views.py
- backend/moment/writing/tests/search_tests.py
- backend/moment/writing/urls.py
> P10: 검색 API 구현

- frontend/Moment/app/build.gradle
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/WriteViewFragmentTest.java
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/utils/CustomViewAction.java
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/utils/CustomViewActions.java
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/utils/LoginAction.java
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/utils/ViewPager2Actions.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/MainActivity.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/data/repository/AuthenticationRepository.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/login/LoginActivity.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/login/LoginViewModel.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/WriteViewFragment.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/utils/CalendarUtilsTest.java
1. 테스트 전 로그인 화면에서 시작해 로그인. 
2. 쓰기 창 진입 후 날짜와 버튼의 가시성 확인
3. 모먼트 추가 버튼을 누른 후 모먼트 수정 창을 클릭할 수 있는지 확인
4. 슬라이드했을 때 과거 기록을 볼 수 있는 창으로 넘어갈 수 있는지 확인
None
> Iter4 P6 Integration Test: Writing Tab

- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/MonthViewFragmentTest.java
- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/StatViewFragmentTest.java
- frontend/Moment/app/src/main/res/layout/fragment_statview.xml
1. 캘린더 뷰 가시성 확인
2. 캘린더 스크롤 후 날짜 확인
3. 통계탭 차트 3개 가시성 확인
4. 통계탭 옵션 선택 버튼 동작 후 기간 확인
None
> Iter4 UI Test: Calendar and Statistics

- frontend/Moment/app/src/androidTest/java/snu/swpp/moment/SearchViewFragmentTest.java
검색 모드에 따라 UI가 제대로 바뀌는지 확인.
None
> Iter4 UI Test: Search

- backend/moment/writing/search_views.py
- backend/moment/writing/tests/search_tests.py
- backend/moment/writing/utils/search.py
* 태그 자동완성과 내용 검색을 할 때 알파벳 대소문자를 무시하도록 구현했습니다.
* 이를 테스트할 수 있는 새로운 test case를 추가했습니다.
> Backend/P3: 검색 시 대소문자 무시

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_monthview/CalendarDayContainer.kt
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_monthview/CalendarDayState.kt
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_monthview/MonthViewFragment.kt
- frontend/Moment/app/src/main/res/layout/calendar_day_info_container.xml
- frontend/Moment/app/src/main/res/layout/calendar_day_info_stat_container.xml
- frontend/Moment/app/src/main/res/values/strings.xml
자동 마무리 관련 calendarView 수정했습니다.
None
> frontend/P9: Show calendar info on auto completed day

- backend/moment/writing/nudge_serializers.py
- backend/moment/writing/nudge_views.py
- backend/moment/writing/tests/__init__.py
- backend/moment/writing/tests/nudge_tests.py
- backend/moment/writing/urls.py
nudge get, post api 구현했습니다. notion - api doc도 업데이트했으니 참고 부탁드려요.
None
> Backend/p4 Implement nudge api

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/ListFooterContainer.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/WritePageState.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/uistate/StoryUiState.kt
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/viewmodel/GetStoryUseCase.java
> Frontend/A1: 자동 마무리 시 쓰기탭 UI 구현

- frontend/Moment/app/src/main/res/layout/fragment_userinfoview.xml
- frontend/Moment/app/src/main/res/layout/user_info_wrapper.xml
1. 닉네임과 밑에 있는 선 모두 가운데 정렬. Nexus 5X와 제 폰에서는 둘 다 가운데 있는 걸로 보였는데 확인해 주세요. 
2. 선 위에 펜 모양과 입력창이 둘 다 있는 건 동일합니다. 닉네임 길게 쓸 때 글씨가 아이콘과 겹치지 않는지 확인해 주세요.
3. 밑줄과 경고창 사이 간격 조금 더 가깝게 조정.
None.
> Iter5 A11: Frontend/design fix/userinfo

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/StoryContainer.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/BaseWritePageFragment.java
마무리 중에는 서버 시간을 모르기 때문에 클라이언트 시간으로 했습니다.
None
> Frontend/a12: 스토리 시간 안보이는 문제 수정

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_statview/StatViewModel.kt
- frontend/Moment/app/src/main/java/snu/swpp/moment/utils/TimeConverter.java
- frontend/Moment/app/src/main/res/layout/fragment_statview.xml
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_statview/StatViewModelTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/DailyViewModelTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/GetStoryUseCaseTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/ui/main_writeview/TodayViewModelTest.java
- frontend/Moment/app/src/test/java/snu/swpp/moment/utils/TimeConverterTest.java
> frontend/A9: 돌아보기 탭 디자인 수정

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/WriteViewFragment.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/ListFooterContainer.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/BaseWritePageFragment.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/DailyViewFragment.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/SlideViewAdapter.java
- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/slideview/TodayViewFragment.java
- frontend/Moment/app/src/main/res/layout/moment_writer.xml
> Iter 5 A4: 프론트 - 쓰기탭 response 대기 중 페이지 이동 이슈 해결

- frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> 프론트: 유저탭 가입 기간 계산 로직 수정
